# Use an official image with g++ pre-installed
FROM gcc:latest

# Set the working directory inside the container
WORKDIR /usr/src/app

# Copy entrypoint script or any initialization file if required (optional)
# ADD entrypoint.sh /usr/src/app/entrypoint.sh

# Run initialization commands if needed
# RUN chmod +x /usr/src/app/entrypoint.sh

# Set default command
CMD ["/bin/bash"]
